heat_template_version: 2014-10-16

description: >
  Change the root password and allow SSH root login for the nodes

resources:
  chpasswd_userdata:
    type: OS::Heat::MultipartMime
    properties:
      parts:
      - config: {get_resource: chpasswd}

  chpasswd:
    type: OS::Heat::SoftwareConfig
    properties:
      config: {get_file: chpasswd.sh}

outputs:
  OS::stack_id:
    value: {get_resource: chpasswd_userdata}
